# Generated by Django 2.0.3 on 2018-03-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('fijo', models.IntegerField()),
                ('correo', models.EmailField(max_length=70)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
    ]
